### ISSUE TITLE
Sublime issues

### ISSUE THREAD

**Issue by scottolsen** [mattbrictson/dotfiles#4]
I followed your instructions and trying to get everything going with sublime but having some issues. The file browser looks broke. Any ideas?

![menubar_and_untitled_ _otk_and_misc_xml_ _otk](https://cloud.githubusercontent.com/assets/113754/13723263/04d80420-e825-11e5-8464-4013b1f7f97e.png)

**Comment by mattbrictson** [comment]
What version of Sublime Text 3 are you using? (In Finder, do "Get Info" on the app to see the version number.) Mine is Build 3107.

**Comment by scottolsen** [comment]
Mine is 3103, I'll give 3107 a shot and see if that fixes things. Thanks!

**Comment by scottolsen** [comment]
Same thing going on

![preferences_sublime-settings_ _otk](https://cloud.githubusercontent.com/assets/113754/13725726/a9c04a48-e86f-11e5-83c7-01e3c97fe336.png)

**Comment by scottolsen** [comment]
Must be something with the theme file. In `Preferences > Settings - User` I reset the theme back to `Default.sublime-theme` and it fixed it.
